@url = http://localhost:5000

###
GET {{url}}/api

###
GET {{url}}

###
GET {{url}}/parking-spots

###
POST {{url}}/parking-spots
Content-Type: application/json

{
    "name": "P1",
    "displayOrder": 1
}

###
@parkingSpotId = 744ee04b-c816-43c8-99e9-6460e5b8ca0d

###
DELETE {{url}}/parking-spots/{{parkingSpotId}}

###
POST {{url}}/reservations
Content-Type: application/json

{
    "userId": "00000000-0000-0000-0000-000000000002",
    "parkingSpotId": "00000000-0000-0000-0000-000000000001",
    "capacity": 2,
    "licensePlate": "ABC123",
    "date": "2022-11-26"
}